POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "nome_completo": "António",
  "email": "antoniojoaquimbernardo2005@gmail.com",
  "senha": "123456",
  "bi": "009373408UE044",
  "telefone": "928776970"
}